#include <stdio.h>
#include "RobotManager.h"

CRobotManager::CRobotManager()
{
  int i;
  for(i = 0; i < MAX_CONNECTED; i++) {
    _connected[i] = false;
    _mobots[i] = NULL;
    _connectedAddresses[i] = NULL;
  }
}

CRobotManager::~CRobotManager()
{
}

bool CRobotManager::isConnected(int index) {
  if((index >= numEntries()) || index < 0) {
    return false;
  }
  return _connected[index];
}

void CRobotManager::setConnected(int index, bool connected)
{
  _connected[index] = connected;
}

int CRobotManager::connect(int availableIndex)
{
  int i;
  int index;
  int err = 0;
  char name[80];
  sprintf(name, "robot%d", numConnected()+1);
  CRecordMobot *mobot = new CRecordMobot(name);
  index = availableIndexToIndex(availableIndex);
  if(err = mobot->connectWithAddress( getEntry(index), 1 )) {
    return err;
  }
  /* Enable the button callback */
  /* FIXME */
  //mobot->enableButtonCallback(CDialogTeaching::OnMobotButton);
  mobot->setJointSpeedRatios(1, 1, 1, 1);
  /* Insert the newly connected robot to the bottom of the list. */
  _mobots[numConnected()] = mobot;
  _connectedAddresses[numConnected()] = 
	  _addresses[availableIndexToIndex(availableIndex)];
  _connected[availableIndexToIndex(availableIndex)] = true;
  return err;
}

int CRobotManager::connectIndex(int index)
{
  if(isConnected(index)) {
    return 0;
  }
  char name[80];
  sprintf(name, "robot%d", numConnected()+1);
  CRecordMobot *mobot = new CRecordMobot(name);
  int err;
  if(err = mobot->connectWithAddress( getEntry(index), 1 )) {
    return err;
  }
  /* Enable the button callback */
  /* FIXME */
  //mobot->enableButtonCallback(CDialogTeaching::OnMobotButton);
  mobot->setJointSpeedRatios(1, 1, 1, 1);
  /* Insert the newly connected robot to the bottom of the list. */
  _mobots[numConnected()] = mobot;
  _connectedAddresses[numConnected()] = 
	  _addresses[index];
  _connected[index] = true;
  return err;
}

int CRobotManager::disconnect(int connectIndex)
{
  int i;
  int foundEntry = 0;
  /* Need to find the ConfigFile index of the connected robot */
  for(i = 0; i < numEntries(); i++) {
    if(_connectedAddresses[connectIndex] == _addresses[i]) {
      foundEntry = 1;
      break;
    }
  }
  if(foundEntry == 0) { return -1; }
  _mobots[connectIndex]->disconnect();
  /* Need to shift addresses and mobots up */
  int j;
  for(j = connectIndex+1; j < numConnected(); j++) {
	_connectedAddresses[j-1] = _connectedAddresses[j];
	_mobots[j-1] = _mobots[j];
  }
  _connected[i] = false;
  return 0; 
}

int CRobotManager::moveUp(int connectIndex) {
  CRecordMobot* tempMobot;
  char* tempAddr;
  if(connectIndex < 1 || connectIndex >= numConnected()) return -1;
  /* Swap the robot with the one prior */
  tempMobot = _mobots[connectIndex-1];
  tempAddr = _connectedAddresses[connectIndex-1];
  _mobots[connectIndex-1] = _mobots[connectIndex];
  _connectedAddresses[connectIndex-1] = _connectedAddresses[connectIndex];
  _mobots[connectIndex] = tempMobot;
  _connectedAddresses[connectIndex] = tempAddr;
  return 0;
}

int CRobotManager::moveDown(int connectIndex) {
  CRecordMobot* tempMobot;
  char* tempAddr;
  if(connectIndex < 0 || connectIndex >= (numConnected()-1)) return -1;
  tempMobot = _mobots[connectIndex + 1];
  tempAddr = _connectedAddresses[connectIndex + 1];
  _mobots[connectIndex+1] = _mobots[connectIndex];
  _connectedAddresses[connectIndex+1] = _connectedAddresses[connectIndex];
  _mobots[connectIndex] = tempMobot;
  _connectedAddresses[connectIndex] = tempAddr;
  return 0;
}

int CRobotManager::numConnected()
{
  int num = 0, i;
  for(i = 0; i < numEntries(); i++) {
    if(_connected[i]) {
      num++;
    }
  }
  return num;
}

const char* CRobotManager::getConnected(int connectIndex) {
	if(connectIndex < 0 || connectIndex >= numConnected()) {
		return NULL;
	}
	return _connectedAddresses[connectIndex];
}

int CRobotManager::availableIndexToIndex(int availableIndex)
{
	int index = 0;
	int i;
	if(availableIndex < 0 || availableIndex > numAvailable()) {
		return -1;
	}
	for(index = 0, i = 0; i <= availableIndex; index++) {
		if(_connected[index] == false) {
			i++;
		}
	}
	index--;
	return index;
}

int CRobotManager::numAvailable()
{
	return numEntries() - numConnected();
}

CRecordMobot* CRobotManager::getMobot(int connectIndex)
{
	if(connectIndex < 0 || connectIndex >= numConnected()) {
		return NULL;
	}
	return _mobots[connectIndex];
}

string* CRobotManager::generateProgram(bool looped)
{
  string buf;
  string *program = new string();
  char tbuf[200];
  int i, j;
  *program += "/* Program generated by RobotController */\n";
  *program += "#include <mobot.h>\n\n";

  /* Declare the appropiate number of CMobot variables */
  for(i = 0; i < numConnected(); i++) {
    sprintf(tbuf, "CMobot robot%d;\n", i+1);
    buf.assign(tbuf);
    *program += buf;
  }

  /* Connect to each one */
  for(i = 0; i < numConnected(); i++) {
    sprintf(tbuf, "robot%d.connectWithAddress(\"%s\", 1);\n", i+1, getMobot(i)->getAddress());
    buf.assign(tbuf);
    *program += buf;
  }

  if(looped) {
    *program += "/* Set the \"num\" variable to the number of times to loop. */\n";
    *program += "int num = 3;\n";
    *program += "int i;\n";
    *program += "for(i = 0; i < num; i++) {";
  }
  /* Now go through each motion */
  for(i = 0; i < getMobot(0)->numMotions(); i++) {
    *program += "\n";
    /* First, print the comment for the motion */
    sprintf(tbuf, "/* %s */\n", getMobot(0)->getMotionName(i));
    buf.assign(tbuf);
    if(looped) *program += "    ";
    *program += buf;
    /* Now, print each robots motion */
    for(j = 0; j < numConnected(); j++) {
      getMobot(j)->getMotionString(i, tbuf);
      buf.assign(tbuf);
      buf += "\n";
      if(looped) *program += "    ";
      *program += buf;
      if(getMobot(j)->getMotionType(i) == MOTION_SLEEP) {
        break;
      }
    }
    /* Make sure all the robots are done moving */
    for(j = 0; j < numConnected(); j++) {
      if(getMobot(j)->getMotionType(i) == MOTION_SLEEP) {
        break;
      }
      sprintf(tbuf, "robot%d.moveWait();\n", j+1);
      buf.assign(tbuf);
      if(looped) *program += "    ";
      *program += buf;
    }
  }
  if(looped) {
    *program += "}\n";
  }
  return program;
}
